using AskLucy.Application.Abstractions;
using AskLucy.Application.Chats.Authorization;
using AskLucy.Domain.Chats;
using MediatR;

namespace AskLucy.Application.Chats.Commands.AppendMessage;

public sealed class AppendMessageCommandHandler(
    IUserChatRepository chatRepository,
    IMessageRepository messageRepository,
    IAIProvider aiProvider,
    IUnitOfWork unitOfWork,
    ICurrentUserAccessor currentUser) : IRequestHandler<AppendMessageCommand, MessageDto>
{
    public async Task<MessageDto> Handle(AppendMessageCommand request, CancellationToken cancellationToken)
    {
        var userId = currentUser.UserId ?? throw new UnauthorizedAccessException();
        var chat = ChatOwnershipGuard.EnsureOwnedBy(await chatRepository.GetByIdAsync(request.ChatId, cancellationToken), userId);

        // Captured before adding the new message so "first message" means what it says —
        // FR-013 derives the auto-title from the conversation's *initial* exchange only,
        // not re-derived from every subsequent user message.
        var isFirstMessage = (await messageRepository.ListByChatIdAsync(request.ChatId, cancellationToken)).Count == 0;

        // FR-016: assistant messages are attributed to the AI provider/model that produced
        // them; a caller may already know these (none do today) and override by supplying
        // them explicitly. Token counts have no equivalent source yet — IAIProvider doesn't
        // surface usage stats — so they stay null until that's added, rather than fabricated.
        var provider = request.Provider ?? (request.Role == MessageRole.Assistant ? aiProvider.ProviderName : null);
        var model = request.Model ?? request.Role switch
        {
            MessageRole.Assistant when request.Kind == MessageKind.Image => aiProvider.ImageModel,
            MessageRole.Assistant => aiProvider.ChatModel,
            _ => null,
        };

        var message = Message.Create(
            request.ChatId, request.Role, request.Kind, request.Content, request.SourceText, userId,
            provider, model, request.GenerationParametersJson,
            request.InputTokenCount, request.OutputTokenCount,
            request.CachedTokenCount, request.ReasoningTokenCount, request.LatencyMs, request.EstimatedCostUsd);

        foreach (var attachment in request.Attachments ?? [])
        {
            message.AddAttachment(attachment.FileName, attachment.ContentType, attachment.AccessLocation, userId);
        }

        foreach (var citation in request.Citations ?? [])
        {
            message.AddCitation(citation.SourceLabel, citation.SourceReference, userId);
        }

        messageRepository.Add(message);
        chat.TouchLastActivity(userId);

        // FR-013: derive an auto-title from the conversation's initial exchange, once, when
        // the conversation has no manually-set title yet (research.md Topic 4) — a no-op via
        // ApplyAutoGeneratedTitle once IsTitleManuallySet is true.
        if (isFirstMessage && request.Role == MessageRole.User)
        {
            chat.ApplyAutoGeneratedTitle(ConversationTitleGenerator.DeriveFrom(request.Content), userId);
        }

        await unitOfWork.SaveChangesAsync(cancellationToken);

        return ToDto(message);
    }

    internal static MessageDto ToDto(Message message) => new(
        message.Id,
        message.Role.ToString(),
        message.Kind.ToString(),
        message.Content,
        message.SourceText,
        message.CreatedAtUtc,
        message.Provider,
        message.Model,
        message.GenerationParametersJson,
        message.InputTokenCount,
        message.OutputTokenCount,
        message.CachedTokenCount,
        message.ReasoningTokenCount,
        message.LatencyMs,
        message.EstimatedCostUsd,
        [.. message.Attachments.Select(a => new AttachmentDto(a.Id, a.FileName, a.ContentType, a.AccessLocation))],
        [.. message.Citations.Select(c => new CitationDto(c.Id, c.SourceLabel, c.SourceReference))]);
}
