using AskLucy.Domain.Common;

namespace AskLucy.Domain.Chats;

/// <summary>
/// A user's saved chat entry — the persisted "Conversation" business concept described in
/// specs/002-chat-history-management/spec.md (research.md Topic 1: this extends the entity
/// rather than introducing a parallel "Conversation" type). Migrated from the legacy
/// int-keyed <c>UserChats</c> table onto the standard entity conventions (spec.md FR-024
/// of SPEC-000); title/session/timestamp fields are otherwise unchanged from that migration.
/// Archive/Pin/Favorite/permanent-delete lifecycle state was added for SPEC-002.
/// </summary>
public sealed class UserChat : BaseEntity
{
    public string Title { get; private set; } = string.Empty;

    public string? SessionId { get; private set; }

    public string UserId { get; private set; } = string.Empty;

    /// <summary>Once true, automatic title generation (FR-013/FR-014) never overwrites <see cref="Title"/> again.</summary>
    public bool IsTitleManuallySet { get; private set; }

    /// <summary>Non-null = archived (FR-006/FR-007); independent of Pinned/Favorite/deleted state.</summary>
    public DateTime? ArchivedAtUtc { get; private set; }

    /// <summary>Non-null = pinned (FR-008); also the sort key for pinned-first ordering.</summary>
    public DateTime? PinnedAtUtc { get; private set; }

    /// <summary>Favorite flag (FR-009), independent of archive/pin/deleted state.</summary>
    public bool IsFavorite { get; private set; }

    private UserChat()
    {
        // Required by EF Core materialization.
    }

    public static UserChat Create(string title, string userId, string? sessionId, string actor)
    {
        if (string.IsNullOrWhiteSpace(title))
        {
            throw new DomainRuleViolationException("A chat title is required.");
        }

        if (string.IsNullOrWhiteSpace(userId))
        {
            throw new DomainRuleViolationException("A chat must belong to a user.");
        }

        return new UserChat
        {
            Id = Guid.CreateVersion7(),
            Title = title.Trim(),
            SessionId = sessionId,
            UserId = userId,
            CreatedAtUtc = DateTime.UtcNow,
            CreatedBy = userId,
        };
    }

    public void Rename(string newTitle, string actor)
    {
        if (string.IsNullOrWhiteSpace(newTitle))
        {
            throw new DomainRuleViolationException("A chat title is required.");
        }

        Title = newTitle.Trim();
        ModifiedAtUtc = DateTime.UtcNow;
        ModifiedBy = actor;
    }

    /// <summary>Marks the title as manually set (FR-014) — called by the rename command handler, not by <see cref="Rename"/> itself, so callers that need a plain title change without freezing auto-titling (none today) remain possible.</summary>
    public void MarkTitleManuallySet() => IsTitleManuallySet = true;

    /// <summary>
    /// Applies an automatically-derived title (FR-013). No-ops once <see cref="IsTitleManuallySet"/>
    /// is true (FR-014) — encapsulated here so every caller gets the rule for free.
    /// </summary>
    public void ApplyAutoGeneratedTitle(string title, string actor)
    {
        if (IsTitleManuallySet || string.IsNullOrWhiteSpace(title))
        {
            return;
        }

        Title = title.Trim();
        ModifiedAtUtc = DateTime.UtcNow;
        ModifiedBy = actor;
    }

    /// <summary>Bumps the last-activity timestamp without changing any other state — called whenever a message is appended, so the "recently updated" sort (FR-021) reflects message activity, not just conversation-level edits (rename/pin/archive/favorite).</summary>
    public void TouchLastActivity(string actor)
    {
        ModifiedAtUtc = DateTime.UtcNow;
        ModifiedBy = actor;
    }

    public void SoftDelete(string actor)
    {
        DeletedAtUtc = DateTime.UtcNow;
        DeletedBy = actor;
    }

    /// <summary>Restores from Archived or Recently Deleted back to the default view (FR-005a/FR-007), preserving prior pin/favorite state — those flags were never touched by archive/delete, so there is nothing to restore on them.</summary>
    public void Restore(string actor)
    {
        DeletedAtUtc = null;
        DeletedBy = null;
        ArchivedAtUtc = null;
        ModifiedAtUtc = DateTime.UtcNow;
        ModifiedBy = actor;
    }

    public void Archive(string actor)
    {
        if (ArchivedAtUtc is not null)
        {
            return;
        }

        ArchivedAtUtc = DateTime.UtcNow;
        ModifiedAtUtc = DateTime.UtcNow;
        ModifiedBy = actor;
    }

    public void Pin(string actor)
    {
        PinnedAtUtc = DateTime.UtcNow;
        ModifiedAtUtc = DateTime.UtcNow;
        ModifiedBy = actor;
    }

    public void Unpin(string actor)
    {
        if (PinnedAtUtc is null)
        {
            return;
        }

        PinnedAtUtc = null;
        ModifiedAtUtc = DateTime.UtcNow;
        ModifiedBy = actor;
    }

    public void MarkFavorite(string actor)
    {
        if (IsFavorite)
        {
            return;
        }

        IsFavorite = true;
        ModifiedAtUtc = DateTime.UtcNow;
        ModifiedBy = actor;
    }

    public void UnmarkFavorite(string actor)
    {
        if (!IsFavorite)
        {
            return;
        }

        IsFavorite = false;
        ModifiedAtUtc = DateTime.UtcNow;
        ModifiedBy = actor;
    }

    public bool IsOwnedBy(string userId) => UserId == userId;
}
