using AskLucy.Application.SiteAnalysis.Commands.CreateSiteAnalysisProjectLinkFromDeepLink;
using AskLucy.Web.Contracts;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;

namespace AskLucy.Web.Controllers.v1;

/// <summary>specs/050-park-site-analysis-agent contracts/site-analysis-api.md. FR-024(a): entry
/// point for a Project-linked deep link generated by TheDigitalCore.</summary>
[ApiController]
[Authorize]
[EnableRateLimiting("site-analysis-endpoints")]
[Route("api/v1/site-analysis")]
public sealed class SiteAnalysisController(ISender mediator) : ControllerBase
{
    [HttpPost("project-links")]
    public async Task<ActionResult<CreateSiteAnalysisProjectLinkFromDeepLinkResponse>> CreateProjectLink(
        CreateSiteAnalysisProjectLinkFromDeepLinkRequest request, CancellationToken cancellationToken)
    {
        var result = await mediator.Send(
            new CreateSiteAnalysisProjectLinkFromDeepLinkCommand(request.TheDigitalCoreProjectId, request.SiteName),
            cancellationToken);
        return Ok(new CreateSiteAnalysisProjectLinkFromDeepLinkResponse(result.UserChatId));
    }
}
