using AskLucy.Application.Abstractions;
using AskLucy.Application.Documents.Authorization;
using AskLucy.Domain.Documents;
using MediatR;

namespace AskLucy.Application.Documents.Queries.GetDocumentPreview;

/// <summary>
/// FR-043, FR-044 — reads the <see cref="DocumentPreview"/> artifact already generated by
/// <c>PreviewGenerationStageHandler</c> (US2); returns <see cref="DocumentPreviewKind.Unavailable"/>
/// rather than erroring whenever no preview exists yet (still processing, processing failed
/// before reaching that stage, or an unsupported format) — never an error state, per FR-044.
/// Markdown is a special case (research.md Decision 6): no <see cref="DocumentPreview"/> row is
/// ever generated for it, since rendering already-extracted plain text as markdown client-side
/// needs no server-side artifact at all.
/// </summary>
public sealed class GetDocumentPreviewQueryHandler(IDocumentRepository documentRepository, ICurrentUserAccessor currentUser)
    : IRequestHandler<GetDocumentPreviewQuery, DocumentPreviewResultDto>
{
    public async Task<DocumentPreviewResultDto> Handle(GetDocumentPreviewQuery request, CancellationToken cancellationToken)
    {
        var userId = currentUser.UserId ?? throw new UnauthorizedAccessException();
        var document = DocumentOwnershipGuard.EnsureOwnedBy(
            await documentRepository.GetByIdAsync(request.DocumentId, cancellationToken), userId);

        if (document.FileType == DocumentFileType.Markdown)
        {
            var markdownVersion = await documentRepository.GetVersionByIdAsync(document.CurrentVersionId, cancellationToken);
            return markdownVersion?.ExtractedText is { } markdownText
                ? new DocumentPreviewResultDto(DocumentPreviewKind.StructuredContent, null, markdownText)
                : DocumentPreviewResultDto.Unavailable;
        }

        var previews = await documentRepository.GetPreviewsByVersionIdAsync(document.CurrentVersionId, cancellationToken);
        if (previews.Count == 0)
        {
            return DocumentPreviewResultDto.Unavailable;
        }

        var structuredContentPreview = previews.FirstOrDefault(p => p.PreviewType == DocumentPreviewType.StructuredContent);
        if (structuredContentPreview is not null)
        {
            var version = await documentRepository.GetVersionByIdAsync(document.CurrentVersionId, cancellationToken);
            return version?.ExtractedStructureJson is { } structureJson
                ? new DocumentPreviewResultDto(DocumentPreviewKind.StructuredContent, null, structureJson)
                : DocumentPreviewResultDto.Unavailable;
        }

        // The first page is enough to satisfy "a rendered preview displays inline" (spec.md US7
        // AC1) without building a full multi-page viewer beyond what's specified.
        var firstRenderedPage = previews
            .Where(p => p.PreviewType is DocumentPreviewType.PageImage or DocumentPreviewType.Thumbnail)
            .OrderBy(p => p.PageNumber ?? 0)
            .FirstOrDefault();

        if (firstRenderedPage is null)
        {
            return DocumentPreviewResultDto.Unavailable;
        }

        var kind = firstRenderedPage.PreviewType == DocumentPreviewType.Thumbnail ? DocumentPreviewKind.Thumbnail : DocumentPreviewKind.PageImage;
        return new DocumentPreviewResultDto(kind, firstRenderedPage.Id, null);
    }
}
