import { Box, Divider, Link, Paper, Stack, Typography } from '@mui/material'
import type { ReactNode } from 'react'
import { Link as RouterLink } from 'react-router'
import { AppFooter } from '../../../components/AppFooter'
import { AppShell } from '../../../components/AppShell'
import { AI_VOICE_DISCLOSURE } from '../../chat/voice/aiVoiceDisclosure'

/** Bump together with the text below; shown to the reader as the terms' effective date. */
export const TERMS_EFFECTIVE_DATE = '2026-09-24'

const VOICE_MODEL_LICENCE_URL = 'https://huggingface.co/Supertone/supertonic-3'

/**
 * The use restrictions of the OpenRAIL-M licence under which Lucy's on-server voice model
 * (Supertonic 3) is served — Attachment A, items (a)–(m). Serving the model as a hosted
 * service counts as distributing it, and the licence (§4.a, §5) requires these restrictions to
 * bind every user "as an enforceable provision"; they are reproduced in substance, not edited
 * down. docs/THIRD_PARTY_NOTICES.md.
 */
const USE_RESTRICTIONS = [
  'in any way that violates any applicable national, federal, state, local or international law or regulation;',
  'to exploit, harm or attempt to exploit or harm minors in any way;',
  'to generate or disseminate verifiably false information or content with the purpose of harming others;',
  'to generate or disseminate personal identifiable information that can be used to harm an individual;',
  'to generate or disseminate content, or place it in any context (for example, a bot posting to social media), without expressly and intelligibly disclaiming that it is machine generated;',
  'to defame, disparage or otherwise harass others;',
  'to impersonate or attempt to impersonate others (for example, deepfakes) without their consent;',
  "for fully automated decision making that adversely impacts an individual's legal rights, or that creates or modifies a binding, enforceable obligation;",
  'for any use intended to, or which has the effect of, discriminating against or harming individuals or groups based on online or offline social behaviour, or known or predicted personal or personality characteristics;',
  'to exploit any of the vulnerabilities of a specific group of persons based on their age or their social, physical or mental characteristics, in order to materially distort the behaviour of a person in that group in a manner that causes, or is likely to cause, that person or another person physical or psychological harm;',
  'for any use intended to, or which has the effect of, discriminating against individuals or groups based on legally protected characteristics or categories;',
  'to provide medical advice or interpret medical results;',
  'to generate or disseminate information for the administration of justice, law enforcement, immigration or asylum processes, such as predicting that an individual will commit fraud or a crime (for example, by text profiling or by drawing causal relationships between assertions made in documents, or through indiscriminate and arbitrarily targeted use).',
]

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <Box component="section">
      <Typography variant="h6" component="h2" sx={{ mb: 1 }}>
        {title}
      </Typography>
      <Stack spacing={1}>{children}</Stack>
    </Box>
  )
}

function Paragraph({ children }: { children: ReactNode }) {
  return (
    <Typography variant="body2" color="text.secondary">
      {children}
    </Typography>
  )
}

/**
 * Public Terms of Service. Reachable without authentication — registered outside
 * `ProtectedRoute` (router.tsx) beside the Privacy Policy. Static, English-only copy like
 * `PrivacyPage`; its effective date is {@link TERMS_EFFECTIVE_DATE}.
 */
export function TermsPage() {
  return (
    <AppShell title="Terms of Service">
      <Box sx={{ display: 'flex', flexDirection: 'column', minHeight: '100%' }}>
        <Box sx={{ flex: 1 }}>
          <Paper elevation={1} sx={{ p: { xs: 3, sm: 4 } }}>
            <Stack spacing={3}>
              <Typography variant="body2" color="text.secondary">
                Effective {new Date(`${TERMS_EFFECTIVE_DATE}T00:00:00Z`).toLocaleDateString(undefined, { timeZone: 'UTC' })}
              </Typography>

              <Section title="1. About these terms">
                <Paragraph>
                  These terms govern your use of Ask Lucy. By creating an account or using the service you agree to
                  them. If you use Ask Lucy on behalf of an organisation, you agree to them on its behalf too.
                </Paragraph>
              </Section>

              <Divider />

              <Section title="2. AI-generated content">
                <Paragraph>
                  Replies, summaries, translations, transcriptions, images and speech produced by Ask Lucy are
                  generated by artificial intelligence. They can be inaccurate, incomplete or out of date. Check
                  anything important before you rely on it. Ask Lucy does not give professional medical, legal,
                  financial or engineering advice.
                </Paragraph>
                <Paragraph>
                  If you publish or share content Ask Lucy generated, you must make clear that it was generated by
                  AI.
                </Paragraph>
              </Section>

              <Divider />

              <Section title="3. Lucy's voice is synthetic">
                <Paragraph>
                  {AI_VOICE_DISCLOSURE} It is produced by text-to-speech: either Supertonic 3, running on our
                  servers, or a third-party voice provider. If you record or share Lucy's spoken replies, you must
                  say that the audio is AI-generated.
                </Paragraph>
              </Section>

              <Divider />

              <Section title="4. Acceptable use">
                <Paragraph>
                  Lucy's on-server voice is Supertone's Supertonic 3 model, which we provide to you under its
                  OpenRAIL-M licence. That licence restricts how the model and its output may be used, and
                  requires those restrictions to bind you. We apply them to the whole of Ask Lucy. You agree not to
                  use Ask Lucy, including Lucy's voice or anything it generates:
                </Paragraph>
                <Box component="ol" type="a" sx={{ m: 0, pl: 3, typography: 'body2', color: 'text.secondary' }}>
                  {USE_RESTRICTIONS.map((restriction) => (
                    <Box component="li" key={restriction} sx={{ mb: 0.5 }}>
                      {restriction}
                    </Box>
                  ))}
                </Box>
                <Paragraph>
                  You also agree not to attack, overload, probe or reverse engineer the service, or to use it to
                  infringe anyone's intellectual property or privacy. We may suspend or close an account that
                  breaks these rules.
                </Paragraph>
              </Section>

              <Divider />

              <Section title="5. Your content and account">
                <Paragraph>
                  You keep ownership of what you upload and write. You give us the permission we need to store and
                  process it to run the service for you, including sending it to the AI providers described below.
                  You are responsible for having the right to upload it and for keeping your sign-in details
                  secure.
                </Paragraph>
              </Section>

              <Divider />

              <Section title="6. Third-party AI providers">
                <Paragraph>
                  To answer you, Ask Lucy sends your prompts, and the files and context they refer to, to the AI
                  providers an administrator has enabled. These can include OpenAI, Anthropic, Google, OpenRouter
                  and ElevenLabs. Their own terms and policies also apply to that processing. How we handle your
                  data is described in the{' '}
                  <Link component={RouterLink} to="/privacy">
                    Privacy Policy
                  </Link>
                  .
                </Paragraph>
              </Section>

              <Divider />

              <Section title="7. Third-party licences">
                <Paragraph>
                  The Supertonic 3 model is © Supertone Inc. and is licensed under the BigScience OpenRAIL-M
                  licence. The use restrictions in section 4 come from paragraph 5 and Attachment A of that
                  licence, which you can read in full on the{' '}
                  <Link href={VOICE_MODEL_LICENCE_URL} target="_blank" rel="noopener noreferrer">
                    model's Hugging Face page
                  </Link>
                  . The code that runs it is used under the MIT licence.
                </Paragraph>
              </Section>

              <Divider />

              <Section title="8. Disclaimers and liability">
                <Paragraph>
                  Ask Lucy is provided "as is", without warranties of any kind, to the extent the law allows. To
                  the extent the law allows, we are not liable for indirect or consequential loss, or for decisions
                  you make based on AI-generated content.
                </Paragraph>
              </Section>

              <Divider />

              <Section title="9. Changes to these terms">
                <Paragraph>
                  We may update these terms. When we do, we will change the effective date above. If you keep
                  using Ask Lucy after a change takes effect, you accept the updated terms.
                </Paragraph>
              </Section>
            </Stack>
          </Paper>
        </Box>
        <AppFooter />
      </Box>
    </AppShell>
  )
}
