using AskLucy.Domain.Chats;
using AskLucy.Domain.Common;
using FluentAssertions;
using Xunit;

namespace AskLucy.Domain.Tests.Chats;

public sealed class UserChatTests
{
    [Fact]
    public void Create_ShouldSetOwnerAndAuditFields()
    {
        var chat = UserChat.Create("My chat", "user-1", "session-1", "user-1");

        chat.Title.Should().Be("My chat");
        chat.UserId.Should().Be("user-1");
        chat.SessionId.Should().Be("session-1");
        chat.CreatedBy.Should().Be("user-1");
        chat.IsDeleted.Should().BeFalse();
    }

    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    public void Create_ShouldThrow_WhenTitleIsBlank(string blankTitle)
    {
        var act = () => UserChat.Create(blankTitle, "user-1", null, "user-1");
        act.Should().Throw<DomainRuleViolationException>();
    }

    [Fact]
    public void Rename_ShouldUpdateTitleAndModifiedAudit()
    {
        var chat = UserChat.Create("Old", "user-1", null, "user-1");
        chat.Rename("New", "user-1");

        chat.Title.Should().Be("New");
        chat.ModifiedBy.Should().Be("user-1");
        chat.ModifiedAtUtc.Should().NotBeNull();
    }

    [Fact]
    public void SoftDelete_ShouldSetDeletedAudit_WithoutRemovingTheEntity()
    {
        var chat = UserChat.Create("Chat", "user-1", null, "user-1");
        chat.SoftDelete("user-1");

        chat.IsDeleted.Should().BeTrue();
        chat.DeletedBy.Should().Be("user-1");
        chat.Title.Should().Be("Chat", "soft delete must not erase the underlying data");
    }

    [Fact]
    public void IsOwnedBy_ShouldReflectTheCreatingUser()
    {
        var chat = UserChat.Create("Chat", "owner-1", null, "owner-1");

        chat.IsOwnedBy("owner-1").Should().BeTrue();
        chat.IsOwnedBy("someone-else").Should().BeFalse();
    }

    [Fact]
    public void Archive_ShouldSetArchivedAtUtc_AndBeIdempotent()
    {
        var chat = UserChat.Create("Chat", "owner-1", null, "owner-1");

        chat.Archive("owner-1");
        var firstArchivedAt = chat.ArchivedAtUtc;
        chat.Archive("owner-1");

        chat.ArchivedAtUtc.Should().Be(firstArchivedAt, "archiving an already-archived conversation is a no-op (FR-006)");
    }

    [Fact]
    public void Restore_ShouldClearArchivedAndDeletedState_PreservingPinAndFavorite()
    {
        var chat = UserChat.Create("Chat", "owner-1", null, "owner-1");
        chat.Pin("owner-1");
        chat.MarkFavorite("owner-1");
        chat.Archive("owner-1");
        chat.SoftDelete("owner-1");

        chat.Restore("owner-1");

        chat.ArchivedAtUtc.Should().BeNull();
        chat.IsDeleted.Should().BeFalse();
        chat.PinnedAtUtc.Should().NotBeNull("restore must preserve prior pin state (FR-005a/FR-007)");
        chat.IsFavorite.Should().BeTrue("restore must preserve prior favorite state (FR-005a/FR-007)");
    }

    [Fact]
    public void Pin_ThenUnpin_ShouldTogglePinnedAtUtc()
    {
        var chat = UserChat.Create("Chat", "owner-1", null, "owner-1");

        chat.Pin("owner-1");
        chat.PinnedAtUtc.Should().NotBeNull();

        chat.Unpin("owner-1");
        chat.PinnedAtUtc.Should().BeNull();
    }

    [Fact]
    public void Unpin_ShouldBeIdempotent_WhenNotPinned()
    {
        var chat = UserChat.Create("Chat", "owner-1", null, "owner-1");

        var act = () => chat.Unpin("owner-1");

        act.Should().NotThrow();
        chat.PinnedAtUtc.Should().BeNull();
    }

    [Fact]
    public void MarkFavorite_ThenUnmarkFavorite_ShouldToggleIsFavorite()
    {
        var chat = UserChat.Create("Chat", "owner-1", null, "owner-1");

        chat.MarkFavorite("owner-1");
        chat.IsFavorite.Should().BeTrue();

        chat.UnmarkFavorite("owner-1");
        chat.IsFavorite.Should().BeFalse();
    }

    [Fact]
    public void MarkTitleManuallySet_ShouldPreventFurtherAutoTitleGeneration()
    {
        var chat = UserChat.Create("Original", "owner-1", null, "owner-1");

        chat.Rename("Manual title", "owner-1");
        chat.MarkTitleManuallySet();
        chat.ApplyAutoGeneratedTitle("Auto-generated title", "owner-1");

        chat.Title.Should().Be("Manual title", "FR-014: a manually-set title is never overwritten by auto-title generation");
    }

    [Fact]
    public void ApplyAutoGeneratedTitle_ShouldSetTitle_WhenNotManuallySet()
    {
        var chat = UserChat.Create("Original", "owner-1", null, "owner-1");

        chat.ApplyAutoGeneratedTitle("Derived title", "owner-1");

        chat.Title.Should().Be("Derived title");
        chat.IsTitleManuallySet.Should().BeFalse("auto-titling itself must not flip the manual flag");
    }

    [Fact]
    public void SetModelSelection_ShouldUpdateProviderModelAndParameters_AndModifiedAudit()
    {
        // specs/005-multi-provider-ai-engine FR-008/FR-009/FR-014.
        var chat = UserChat.Create("Chat", "owner-1", null, "owner-1");
        var providerId = Guid.NewGuid();
        var modelId = Guid.NewGuid();

        chat.SetModelSelection(providerId, modelId, "{\"temperature\":0.5}", "owner-1");

        chat.ProviderId.Should().Be(providerId);
        chat.ModelId.Should().Be(modelId);
        chat.GenerationParametersJson.Should().Be("{\"temperature\":0.5}");
        chat.ModifiedBy.Should().Be("owner-1");
        chat.ModifiedAtUtc.Should().NotBeNull();
    }
}
